name: Continuous Integration
on: [push]
jobs:
  call-continuous-integration-reusable:
    uses: lalith-org/github-reusable-workflows/.github/workflows/ci.yml@main
    with:
      project_name: expense-backend
      npm_install: true
    secrets: inherit