name: Continuous Integration
on: [push]
jobs:
  call-release-reusable:
    uses: lalith-org/github-reusable-workflows/.github/workflows/release.yml@main
    with:
      project_name: expense-backend
      npm_install: true
    secrets: inherit
